name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAI’s ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'Your Name or Organization'

inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  REPOSITORY:
    description: 'The repository where the action will be executed.'
    required: true
  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  SCRIPT_PATH:
    description: 'The path to the script that interacts with ChatGPT and generates code.'
    required: true
  LABEL:
    description: 'Allows users to customize the label that triggers the action.'
    required: true

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config --local user.name "autocoder-bot"
        git config --local user.email "actions@github.com"
      shell: bash  # Added shell property here

    - name: Make the Script Executable
      run: chmod +x ./${{ inputs.SCRIPT_PATH }}
      shell: bash  # Added shell property here

    - name: Generate Code from Issue
      id: generate_code
      run: ./scripts/script.sh ${{ inputs.GITHUB_TOKEN }} ${{ inputs.REPOSITORY }} ${{ inputs.ISSUE_NUMBER }} ${{ inputs.OPENAI_API_KEY }}
      shell: bash  # Added shell property here

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-bot/

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-artifact/

    - name: List Files
      run: ls -R ./autocoder-artifact
      shell: bash  # Added shell property here

    - name: Commit Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "autocoder-bot"
        git add .
        git commit -m "Add generated code from ChatGPT"
      shell: bash  # Added shell property here

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        labels: "autocoder-bot"
        author: autocoder-bot <actions@github.com>
        title: "#${{ github.event.issue.number }}"
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}
