
name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'Your Name or Organization'

inputs:
  REPOSITORY:
    description: 'The repository where the action will be executed.'
    required: true
  SCRIPT_PATH:
    description: 'The path to the script that interacts with ChatGPT and generates code.'
    required: false
    default: scripts/script.sh
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  ISSUE_NUMBER:
    description: 'The number fo the issue that triggered the action.'
    required: true
  LABEL:
    description: 'The label assigned to GitHub issues that should be processed by the AutoCoder action. Only issues with this label will trigger the code generation process.'
    required: true
    default: 'autocoder-bot'

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'

runs:
  using: 'composite'
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    REPOSITORY: ${{ inputs.repository }}
    ISSUE_NUMBER: ${{ inputs.ISSUE_NUMBER }}
    OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    SCRIPT_PATH: ${{ inputs.SCRIPT_PATH }}

  steps:
    - name: Greet Users
      run: echo "Hello, welcome to AutoCoder! Let's generate some code."
      shell: bash

    - name: Generate Code from Issue
      id: generate_code

      run: ./${{ inputs.SCRIPT_PATH }} ${{ inputs.GITHUB_TOKEN }} ${{ inputs.REPOSITORY }} ${{ inputs.ISSUE_NUMBER }} ${{ inputs.OPENAI_API_KEY }}
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-bot/

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-artifact/

    - name: List Files
      run: ls -R ./autocoder-artifact

    - name: Commit Changes
      run: |
        git config --local user.name "autocoder-bot"
        git config --local user.email "actions@github.com"
        git add ./autocoder-artifact
        git commit -m "Add generated code from ChatGPT"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        labels: "autocoder-bot"
        author: autocoder-bot <actions@github.com>
        title: "PR to issue #${{ inputs.ISSUE_NUMBER }}"
        branch: autocoder-branch-${{ inputs.ISSUE_NUMBER }}