name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'Your Name or Organization'

inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  REPOSITORY:
    description: 'The repository where the action will be executed.'
    required: true
  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  SCRIPT_PATH:
    description: 'The path to the script that interacts with ChatGPT and generates code.'
    required: false
    default: scripts/script.sh
  LABEL:
    description: 'Allows users to customize the label that triggers the action.'
    required: false
    default: autocoder-bot

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'

runs:
  using: 'composite'

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Configure Git
      run: |
        git config --local user.name "autocoder-bot"
        git config --local user.email "actions@github.com"
      shell: bash

    - name: make the script executable
      run: chmod +x ${{ github.action_path }}/${{ inputs.SCRIPT_PATH }}
      shell: bash

    - name: Generate Code with ChatGPT
      id: generate_code
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REPOSITORY: ${{ inputs.repository }}
        ISSUE_NUMBER: ${{ inputs.issue.number }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      run:  ${{ github.action_path }}/${{ inputs.SCRIPT_PATH }} $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-bot/

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: autocoder-artifact
        path: autocoder-artifact/

    - name: List Files
      run: ls -R ./autocoder-artifact
      shell: bash

    - name: Commit Changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "autocoder-bot"
        git add .
        git commit -m "Add generated code from ChatGPT"
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        labels: "autocoder-bot"
        author: autocoder-bot <actions@github.com>
        title: "#${{ github.event.issue.number }}"
        branch: autocoder-branch-${{ inputs.issue.number }}