ame: Autocoder Bot Workflow

on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  generate_code:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Set permissions for script.sh
        run: chmod +x scripts/script.sh
 
      - name: Check if issue has 'autocoder-bot' label
        id: check_label
        run: |
          labels=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[] | .name')
          if echo "$labels" | grep -q 'autocoder-bot'; then
            echo "has_label=true" >> $GITHUB_ENV
          else
            echo "has_label=false" >> $GITHUB_ENV
          fi
      - name: Run script.sh
        if: env.has_label == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY
 
      - name: Upload generated files as artifacts
        if: env.has_label == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: autocoder-artifact
          path: ./autocoder-bot
 
      - name: Download artifacts
        if: env.has_label == 'true'
        uses: actions/download-artifact@v2
        with:
          name: autocoder-artifact
          path: ./autocoder-artifact
 
      - name: List files in artifact
        if: env.has_label == 'true'
        run: ls -R ./autocoder-artifact