name: Access Issue Information
on:
  issues:
    types: [opened, reopened]
jobs:
  access_issue_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Issue Information
        run: |
          echo "Issue Number: $ISSUE_NUMBER"
          echo "Issue Title: $ISSUE_TITLE"
          echo "Issue Body: $ISSUE_BODY"
          echo "Issue Assignees: $ISSUE_ASSIGNEES"
          echo "Issue Labels: $ISSUE_LABELS"
          ISSUE_RESPONSE=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_NUMBER})
          echo "Issue Information: $ISSUE_RESPONSE"
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
          GITHUB_REPOSITORY: ${{ github.repository }}

